site_name: "Dare Badejo Portfolio"
site_url: "https://Dare-Badejo-001.github.io/"
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "deep orange"
  font:
    text: "Inter"
    code: "Fira Code"
nav:
  - Home: index.md
  - About: about.md
  - Work: work.md
  - Research: research.md
  - Insights: insights.md
  - Impact: impact.md
  - Contact: contact.md
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js